// packages/create-widget/views/svelte/template/src/component/View.svelte
<script>
  import { setContext } from 'svelte';
  import {writable} from 'svelte/store';

  import Welcome from './Welcome.svelte';
  import WidgetDescription from './WidgetDescription.svelte';
  import Counter from './Counter.svelte';
  import ErrorView from './ErrorView.svelte';
  
  export let widget;
  export let state;
  export let props;

  let reactiveState = writable(state);
  let reactiveProps = writable(props);

  setContext('widget', widget);
  setContext('props', reactiveProps);
  setContext('state', reactiveState);

  $: {
    $reactiveState = state;
    $reactiveProps = props;
  }
</script>

{#if widget.error }
  <ErrorView /> 
{/if}


{#if !widget.error }
  <div class="merkur__page">
    <div class="merkur__headline">
      <div class="merkur__view">
        <Welcome />
        <WidgetDescription name={widget.name} version={widget.version}/>
      </div>
    </div>
    <div class="merkur__view">
      <Counter />
    </div>
  </div>
{/if}

// packages/create-widget/views/preact/src/component/View.jsx
import { h } from 'preact';
import WidgetContext from './WidgetContext';
import MerkurIcon from './MerkurIcon';
import Welcome from './Welcome';
import WidgetDescription from './WidgetDescription';
import Counter from './Counter';

export default function View(widget) {
  return (
    <WidgetContext.Provider value={widget}>
      <div className="merkur__page">
        <div className="merkur__headline">
          <div className="merkur__view">
            <MerkurIcon />
            <Welcome />
            <WidgetDescription name={widget.name} version={widget.version} />
          </div>
        </div>
        <div className="merkur__view">
          <Counter counter={widget.state.counter} />
        </div>
      </div>
    </WidgetContext.Provider>
  );
}
