// packages/create-widget/views/preact/template/src/views/View.jsx
import ErrorView from './ErrorView';
import Counter from '../components/Counter';
import WidgetContext from '../components/WidgetContext';

function View(widget) {
  if (widget.error && widget.error.status) {
    return <ErrorView error={widget.error} />;
  }

  return (
    <WidgetContext.Provider value={widget}>
      <div className='merkur__page'>
        <div className='merkur__view'>
          <Counter counter={widget.state.counter} />
        </div>
      </div>
    </WidgetContext.Provider>
  );
}

export default View;

// packages/create-widget/views/svelte/template/src/views/View.svelte
<script>
  import { setContext } from 'svelte';
  import { writable } from 'svelte/store';

  import Counter from '../components/Counter.svelte';
  import ErrorView from '../components/ErrorView.svelte';

  export let widget;
  export let state;
  export let props;

  let reactiveState = writable(state);
  let reactiveProps = writable(props);

  setContext('widget', widget);
  setContext('props', reactiveProps);
  setContext('state', reactiveState);

  $: {
    $reactiveState = state;
    $reactiveProps = props;
  }
</script>

{#if widget.error && widget.error.message }
  <div>
    <ErrorView />
  </div>
{:else}
  <div class="merkur__page">
    <div class="merkur__view">
      <Counter />
    </div>
  </div>
{/if}
