// packages/create-widget/views/react/template/src/views/View.jsx
import React from 'react';
import WidgetContext from '../component/WidgetContext';
import Counter from '../component/Counter';
import ErrorView from '../component/ErrorView';
import { headlineSlotFactory } from '../slots/HeadlineSlot';

async function viewFactory(widget) {
  return {
    View: View,
    containerSelector: '.merkur-view',
    slots: await Promise.all([headlineSlotFactory(widget)]),
  };
}

function View(widget) {
  if (widget.error && widget.error.status) {
    return <ErrorView error={widget.error} />;
  }

  return (
    <WidgetContext.Provider value={widget}>
      <div className="merkur__page">
        <div className="merkur__view">
          <Counter counter={widget.state.counter} />
        </div>
      </div>
    </WidgetContext.Provider>
  );
}

export { viewFactory };
export default View;

// packages/create-widget/views/svelte/template/src/views/View.svelte
<script>
  import { setContext } from 'svelte';
  import { writable } from 'svelte/store';

  import Counter from './Counter.svelte';
  import ErrorView from './ErrorView.svelte';

  export let widget;
  export let state;
  export let props;

  let reactiveState = writable(state);
  let reactiveProps = writable(props);

  setContext('widget', widget);
  setContext('props', reactiveProps);
  setContext('state', reactiveState);

  $: {
    $reactiveState = state;
    $reactiveProps = props;
  }
</script>

{#if widget.error }
  <ErrorView />
{/if}


{#if !widget.error }
  <div class="merkur__page">
    <div class="merkur__view">
      <Counter />
    </div>
  </div>
{/if}
