// packages/create-widget/views/preact/template/src/slots/HeadlineSlot.jsx
import { createSlotFactory } from '@merkur/core';

import Welcome from '../components/Welcome';
import WidgetContext from '../components/WidgetContext';
import WidgetDescription from '../components/WidgetDescription';

const headlineSlotFactory = createSlotFactory(() => ({
  name: 'headline',
  View: HeadlineSlot,
}));

function HeadlineSlot(widget) {
  if (widget.error && widget.error.status) {
    return null;
  }

  return (
    <WidgetContext.Provider value={widget}>
      <div className='merkur__headline'>
        <div className='merkur__view'>
          <Welcome />
          <h3>Current count: {widget.state.counter}</h3>
          <WidgetDescription name={widget.name} version={widget.version} />
        </div>
      </div>
    </WidgetContext.Provider>
  );
}

export { headlineSlotFactory };
export default HeadlineSlot;

// packages/create-widget/views/svelte/template/src/slots/HeadlineSlot.svelte
<script>
  import { setContext } from 'svelte';
  import { writable } from 'svelte/store';

  import Welcome from '../components/Welcome.svelte';
  import WidgetDescription from '../components/WidgetDescription.svelte';
  import ErrorView from '../components/ErrorView.svelte';

  export let widget;
  export let state;
  export let props;

  let reactiveState = writable(state);
  let reactiveProps = writable(props);

  setContext('widget', widget);
  setContext('props', reactiveProps);
  setContext('state', reactiveState);

  $: {
    $reactiveState = state;
    $reactiveProps = props;
  }
</script>

{#if widget.error && widget.error.message }
  <div>
    <ErrorView />
  </div>
{:else}
  <div class="merkur__page">
    <div class="merkur__headline">
      <div class="merkur__view">
        <Welcome />
        <h3>Current count: {state.counter}</h3>
        <WidgetDescription name={widget.name} version={widget.version}/>
      </div>
    </div>
  </div>
{/if}
