// packages/create-widget/views/react/template/src/component/Counter.jsx
import React, { useContext } from 'react';
import WidgetContext from './WidgetContext';

export default function Counter({ counter }) {
  const widget = useContext(WidgetContext);

  return (
    <div>
      <h3>Counter widget:</h3>
      <p>Count: {counter}</p>
      <button onClick={widget.onClick}>increase counter</button>
      <button onClick={widget.onReset}>reset counter</button>
    </div>
  );
}

// packages/create-widget/views/svelte/template/src/component/Counter.svelte
<script>
  import { getContext } from 'svelte';

	const widget = getContext('widget');
  const state = getContext('state');
</script>


<div>
  <h3>Counter widget:</h3>
  <p>Count: <span id="counter">{$state.counter}</span></p>
  <button on:click={widget.onClick}>
    increase counter
  </button>
  <button on:click={widget.onReset}>
    reset counter
  </button>
</div>
